// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXcGlUW4Nm_Zch3npYs7Di6FpMM60ty4g',
    appId: '1:209912157590:web:3302fb317db306f8d839b7',
    messagingSenderId: '209912157590',
    projectId: 'assistant-project-f4d87',
    authDomain: 'assistant-project-f4d87.firebaseapp.com',
    databaseURL: 'https://assistant-project-f4d87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assistant-project-f4d87.appspot.com',
    measurementId: 'G-65VMD28J1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFqvS2RpQiHhowRMichFXTAl4W03KZ24',
    appId: '1:209912157590:android:32bde7bbe6648f23d839b7',
    messagingSenderId: '209912157590',
    projectId: 'assistant-project-f4d87',
    databaseURL: 'https://assistant-project-f4d87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assistant-project-f4d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4qjcImY6X6I8qanNTPH4LzQSZHXV8tNk',
    appId: '1:209912157590:ios:86da88be362bc651d839b7',
    messagingSenderId: '209912157590',
    projectId: 'assistant-project-f4d87',
    databaseURL: 'https://assistant-project-f4d87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assistant-project-f4d87.appspot.com',
    iosBundleId: 'com.example.employerProject',
  );
}
